include("./fun_fs/types.jl")
include("./fun_fs/topol.jl")
include("./fun_fs/BSpline.jl")
include("./fun_fs/accum.jl")
include("./fun_fs/solve.jl")
include("./fun_fs/flip.jl")
include("./fun_fs/DMBC.jl")
include("./fun_fs/elast.jl")
include("./fun_fs/plast.jl")

#include("../../src/GRFS_gauss.jl")
include("./fun/GRFS_exp.jl")
include("./fun/functionsT.jl")
include("./fun/RFS.jl")