include("types.jl")
include("topol.jl")
include("BSpline.jl")
include("accum.jl")
include("solve.jl")
include("flip.jl")
include("DMBC.jl")
include("elast.jl")
include("plast.jl")

#include("../../src/GRFS_gauss.jl")
include("GRFS_exp.jl")
include("functionsT.jl")
include("RFS.jl")